GET http://localhost:5159/Producto
Accept: application/json


GET http://localhost:5159/api/Producto/1
Accept: application/json

POST http://localhost:5159/api/Producto HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Fundamentos en Pixel Art",
    "descripcion": "En este curso diseñaras artes creado de forma digital basado en píxeles, utilizando herramientas de edición de imagen sencillas.",
    "precio": 200,
    "porcentajeDescuento": 40,
    "imageName": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaouZKAZEFr57ujTkjRYvGBBE1j8i7hetNaH_jo7fHLFq9alKQInapHoh2pQdn5SngS-4&usqp=CAU",
    "status": "Activo"
}