GET http://localhost:5159/Producto
Accept: application/json


GET http://localhost:5159/api/Producto/1
Accept: application/json

POST http://localhost:5159/api/Producto HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "GG NOMAS",
    "descripcion": "Es un lenguaje de programacion general tipado, orientado a objetos, que permite el desarrollo desde aplicaciones basicas",
    "precio": 190,
    "porcentajeDescuento": 60,
    "imageName": "https://cdn2.dineroenimagen.com/media/dinero/styles/gallerie/public/images/blogs/javalogo.jpg",
    "status": "Activo"
}